### PR TITLE
Add chintu in names.txt

### PR DESCRIPTION
**Pull request by saibhaskar-ch**
Add new name chintu in the names.txt

### CODE REVIEW

**Comment by Ironman2910** [comment]
pls add more description  for me to understand this PR

**Comment by saibhaskar-ch** [comment]
I added a new name called "CHINTU" in the names.txt file . It is the name of the dog.

**Comment by Ironman2910** [comment]
cool! will approve PR

**Review by Ironman2910 — APPROVED** [review]
Looks good.

**Pull request merged**
